// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for S3BucketPolicyUpdaterFunction
 */
export interface S3BucketPolicyUpdaterFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/lambda/s3-bucket-policy-updater.
 */
export class S3BucketPolicyUpdaterFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: S3BucketPolicyUpdaterFunctionProps) {
    super(scope, id, {
      description: 'src/lambda/s3-bucket-policy-updater.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs24.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/lambda/s3-bucket-policy-updater.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}